### ISSUE TITLE
Partage de données en JSON entre VueJS & PHP

### ISSUE THREAD

**Issue by CoralieGold** [Web-Imac-2017/Groupe5#1]
On a un petit soucis au niveau de la liaison back / front :
On veut récupérer des données du back en VueJS, après avoir faire un post.

**BACK :** 
`echo json_encode($data);`

**FRONT :** 
```
this.$http.post(apiRoot() + 'monFichier.php', {pseudo: this.pseudo}, {headers : {'Content-Type' : 'application/form-data; charset=UTF-8'}}).then(function(response) {
console.log(response);
console.log(response.data);
console.log(response.json());
});
```

Lorsque les tests sont faits sur Postman, on voit bien qu'on echo en back (on a un objet JSON avec les bonnes données), mais le front n'a pas l'air de le récupérer car les data sont undefined (et response a bien un "status:200").

Je pense donc que le problème vient du front, mais je ne vois pas où, comme je fais exactement ce que j'ai pu voir sur la doc.

**Comment by YellowFish085** [comment]
@CoralieGold  Je ne sais pas ce que c'est que `this.$http.post`. Si vous avez bien le JSON qui ressort du back c'est qu'effectivement il y a un blème en front.

Déjà si c'est pas déjà fait regardez dans le devtool de Chrome, dans l'onglet Network, voir la réponse concrète qui est récupérée par le call ajax. Ca vous permettra de voir si vous avez bien un JSON qui ressort (et donc que c'est au niveau du code js que vous avez foiré quelque chose, par exemple dans le callback ( le `.then(function(response) ...` )) ou si y'a rien du tout qui est récupéré (et donc que potentiellement vous appelez pas le bon fichier de l'api, ou que y'a une redirection via .htaccess qui fait de la merde, ou alors que le fichier php fait un echo d'un truc vide à un moment qui court-circuite le reste, ou encore que la manière dont vous créez votre call AJAX en js est foiré par exemple).

Ensuite, essayez d'utiliser `fetch` qui est une API js pour faire des call AJAX. Y'a des packages npm pour rendre l'API compatible avec tous les navigateurs ( https://github.com/YellowFish085/imac2-12-01/blob/master/package.json les packages `es6-promise` et `isomorphic-fetch` )

Checkez les liens suivant pour un peu d'info sur comment l'utiliser :
- https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch
- https://davidwalsh.name/fetch

**Comment by CoralieGold** [comment]
@YellowFish085 
J'ai testé `fetch`, mais le résultat est le même.

Sur Postman, j'ai bien ça : (donc le back fonctionne)

![image](https://cloud.githubusercontent.com/assets/16426504/23214687/f04364ee-f90f-11e6-8a1c-7d2821704cb6.png)


Quand je regarde dans le devtool de Chrome, j'ai ça : 

![image](https://cloud.githubusercontent.com/assets/16426504/23214762/3564d76a-f910-11e6-846d-2d1a86828cbb.png)

Le code en front est :
```php
var form = new FormData();
form.append('pseudo', this.pseudo);
form.append('password', this.password)
fetch(apiRoot() + 'Controllers/User/login.php', {
method: 'POST',
headers: {
'Accept': 'application/json, application/xml, text/plain, text/html, *.*',
'Content-Type': 'application/json; charset=utf-8'
},
dataType: 'JSON',
body: form
}).then(function(response) {
console.log(response);
})```

J'ai aussi essayé avec `'Content-Type': 'application/form-data; charset=utf-8'`.

On a bien accès au fichier .php normalement, car quand l'url était faux, il y avait une erreur type "not found".

**Comment by YellowFish085** [comment]
T'as essayé de virer tout ton code php et de juste faire genre un
```php
<?php
  echo 'test';
?>
```
histoire de voir si ton fichier est bien capable de renvoyer quelque chose, ou si y'a juste rien du tout du tout qui est renvoyé. Essaie aussi de virer les lignes en js pour forcer du JSON en retour (histoire d'être sur que tu peux recevoir tout type de réponse).

Après je remarque aussi que tu envoie aucun paramètre POST à la page login.php dans ton code javascript, alors que dans Postman tu lui file des params POST...

J'ai pas ton code complet et je peux pas test, mais au vu de ta dernière réponse si ce que j'ai mis au dessus marche pas :
- 1) Virer tout ce qui force du JSON en réponse dans le javascript
- 2) Virer tout ton code php pour mettre un simple `echo`
- 3) Test si tu reçoit quelque chose
- 4) si oui, remettre progressivement le code (genre remettre le js, ensuite remettre petit à petit le php) jusqu'à trouver la ligne qui pose problème
- 5) si tu reçoit rien, je sais pas trop quoi te dire :/

**Comment by CoralieGold** [comment]
C'est bon, le problème venait du back, avec un if qui empêchait un echo correct.
Merci de l'aide !

**Comment by CoralieGold** [comment]
@YellowFish085 

J'ai corrigé le problème et récupère bien les données grâce à `fetch`, mais le soucis c'est qu'il ne connait pas le `this`.
Je m'explique : je fais mon post dans un component et le `fetch` dans une méthode de `export default`. Mais, si je veux faire quelque chose du type `this.loginError = data`, le `this` est considéré comme undefined (avec évidemment

```javascript
data : function () {
      return {
        loginError: ''}}`). Est-ce normal ? Y a-t-il un moyen de corriger cela ? 

Code complet (front) :
`import {apiRoot} from '../../config/localhost/settings.js'

  export default {
    data : function () {
      return {
        loginError: '',
        pseudo: '',
        password: '',
        submit: ''
      }
    },
    methods: {
      login: function() {
        fetch(apiRoot() + 'Controllers/User/login.php', {
          method: 'POST',
          headers: {
            'Accept': 'application/json, application/xml, text/plain, text/html, *.*',
            'Content-Type': 'application/json; charset=utf-8'
          },
          dataType: 'JSON',
          body: JSON.stringify({pseudo : this.pseudo, password : this.password})
        }).then(function(response) {
          return response.json();
        }).then(function(data){
          if(data[0] == "Error"){
            this.loginError = data[1];
          }
          else {
            this.$router.push('/home/');
          }
        });
      }
    }
  }
```

**Comment by YellowFish085** [comment]
C'est un problème de contexte. En gros, quand tu es dans la méthode `login`, tu peux faire `this.loginError`.
Par contre, quand tu es dans un `then(function() { ... ` le `this` fait plus référence à la même chose (ici, à ton component VueJS).
Pour plus d'infos http://javascriptplayground.com/blog/2012/04/javascript-variable-scope-this/ et https://scotch.io/tutorials/understanding-scope-in-javascript#context

Pour ton problème, deux moyens :
1) au début de ta méthode `login` tu fait comme dans le premier lien au dessus, un `var _this = this` et ensuite si tu à besoin d'utiliser `this` tu utilises à la place `_this`. Note que tu peux mettre ce que tu veux à la place de `_this` (genre souvent c'est `that` qui est utilisé).
2) Au lieux d'appeller une fonction direct comme tu le fais via `.then(function(data) { ... ` tu appelle une méthode que tu défini comme t'as définit la méthode `login`.
Du genre au lieu de
```javascript
...
}).then(function(data){
   if(data[0] == "Error"){
      this.loginError = data[1];
   }
   else {
      this.$router.push('/home/');
   }
});
...
```

tu fais

```javascript
...
}).then(this.monCallback(data));
...
```
ou `monCallback` est une méthode définie comme ta méthode `login`.

Pour le 1) c'est simple à faire et ça marche sur, mais c'est pas ouf propre je trouve.
Pour le 2) c'est mieux, mais par contre je suis pas sur que ça marche, j'ai peur que tu te retrouve avec exactement le même problème. Si jamais tu te retrouve effectivement avec le mêm, problème, essaie de rajouter un `this.monCallback = this.monCallback.bind(this);` au tout début de la méthode `login`, ça devrait marcher (mais pas sur encore). Si jamais t'as besoin de rajouter la ligne dis moi j'expliquerai pourquoi.

---

Edit:  Pour info, tu peux ecrire du code multiligne en utilisant \``` au lieu de juste \`.
Tu peux aussi préciser le langage genre :
\```javascript
console.log('coucou');
\```
te donnera
```javascript
console.log('coucou');
```

---

Edit bis : par contre la tu exporte un objet javascript ` { ... } ` pas un objet VueJS.
